image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:clu-update-dev-env-image.0
workspaceLocation: gitpod/gitpod-ws.theia-workspace
checkoutLocation: gitpod
ports:
  - port: 1337
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
  - port: 3001
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  - port: 4000
    onOpen: ignore
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 9229
    onOpen: ignore
# Go proxy
  - port: 9999
    onOpen: ignore
  - port: 13001
    onOpen: ignore
# Werft
  - port: 7777
    onOpen: ignore
# Dev Theia
  - port: 13444
tasks:
  - before: scripts/branch-namespace.sh
    init: yarn --network-timeout 100000 && yarn build
  - name: Go
    init: leeway exec --filter-type go -v -- go get -v ./...
    openMode: split-right
vscode:
  extensions:
    - golang.go
    - hangxingliu.vscode-nginx-conf-hint@0.1.0
    - zxh404.vscode-proto3@0.4.2
    - ms-kubernetes-tools.vscode-kubernetes-tools@1.2.1
    - bajdzis.vscode-database@2.2.1
    - hashicorp.terraform@2.1.1
    - stkb.rewrap@1.13.0