{{ if .Values.installPodSecurityPolicies -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: poolkeeper
  labels:
    {{- include "poolkeeper.labels" . | nindent 4 }}
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - poolkeeper
{{- end -}}